spring:
  application:
  name: api-gateway

#api gateway config
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/v1/book/**
          filters:
            - StripPrefix=2
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2

#eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka